target("gemini_test", function () 
    set_kind("binary")
    add_files("src/gemini_test.cpp")
    add_includedirs("include", {public = true})
end)

target("cutertspserver", function ()
    set_kind("static")
    add_files("src/rtp.cpp")
    add_includedirs("include", {public = true})
end)